name: sig_mobile
description: Application Mobile de Relevé Cartographique (SIG) pour l'agence urbaine
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Base de données
  sqflite: ^2.3.0
  path: ^1.8.3

  # Carte et géolocalisation
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geolocator: ^10.1.0
  permission_handler: ^11.0.1

  # Interface utilisateur
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.0

  # Gestion d'état
  provider: ^6.1.1

  # Utilitaires
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  
  # Itinéraire et navigation
  flutter_polyline_points: ^2.0.0
  url_launcher: ^6.2.0
  
  # Graphiques avancés
  fl_chart: ^0.66.0
  
  # Export PDF
  pdf: ^3.10.0
  printing: ^5.12.0
  
  # Photos
  image_picker: ^1.0.4
  
  # KML/GPX
  xml: ^6.3.0
  
  # Clipboard
  clipboard: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
